name = "hello-world"
main = "src/index.ts"
compatibility_date = "2023-11-12"


[[durable_objects.bindings]]
name = "DURABLE"
class_name = "DurableSocket"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["DurableSocket"]